const _ = [
  'text-orange',
  'text-orange-light',
  'text-orange-dark',
  'text-yellow',
  'text-yellow-light',
  'text-yellow-dark',
  'text-green',
  'text-green-light',
  'text-green-dark',
  'text-teal',
  'text-teal-light',
  'text-teal-dark',
  'text-blue',
  'text-blue-light',
  'text-blue-dark',
  'text-indigo',
  'text-indigo-light',
  'text-indigo-dark',
  'text-purple',
  'text-purple-light',
  'text-purple-dark',
  'text-pink',
  'text-pink-light',
  'text-pink-dark',
  'hover:animate-fadeIn',
  'hover:animate-fadeOut',
  'hover:animate-rotation-360',
  'hover:animate-rotation-360-reverse'
];

export default _;
